### PR TITLE
Fix rotation matrix inversion issue in HOA.

### PR DESCRIPTION
**Pull request by drewbitllama**
Forgot to build library.

### CODE REVIEW

**Comment by drewbitllama** [comment]
Modified tests in order for changes to work and be tested properly.

**Comment by hoch** [comment]
@drewbitllama Can you take a look at Travis CI build? It seems to be failing on the rotation test.

**Comment by drewbitllama** [comment]
I'll tal tomorrow.

**Comment by drewbitllama** [comment]
This patch is passing on my machine. Is the TravisCL setup to use the latest tests even when we are updating the test files?

**Comment by hoch** [comment]
It might be numeric differences between platforms. If that's the case we might want to loosen the threshold a bit.

**Comment by hoch** [comment]
"Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves."

I see this message in the log.

**Comment by hoch** [comment]
I just confirmed that this PR does not pass the test locally.

```js
var forward = [
      __-__Math.sin(azimuth) * Math.cos(elevation), Math.sin(elevation),
      __-__Math.cos(azimuth) * Math.cos(elevation)
];
```

The added minus signs broke the test and my failed log is identical to the one from Travis CI. Needs further investigation...

**Comment by hoch** [comment]
@drewbitllama Okay, here's how we got here:

1. The 3rd order rotation formula [changed and merged](https://github.com/GoogleChrome/omnitone/pull/86/files).
2. The PR broke the build because the built library was not included in the PR.
3. The PR in 2 was reverted.
4. The [second PR](https://github.com/GoogleChrome/omnitone/pull/87/files) was introduced the fix the test accordingly.
5. However, this PR also could not pass the test because it did not have the change in 1.

So when I sum 1 and 4 into one PR and it passes the test, but now we have a bigger issue. The rotation direction has been reversed. This is a breaking change and I suggest we should not do this at this point.

Could you clarify why we need this so much?

**Comment by drewbitllama** [comment]
If we don’t do this (currently the case) we get opposite behaviors for
foarenderer.setmatrix and hoarenderer.setmatrix (the rotation goes the
other way)

**Comment by hoch** [comment]
I see. That's much bigger issue. So are you suggesting we bite the bullet and make this change? I guess this issue was found while you're dynamically switching between FOA/HOA renderer?

**Comment by drewbitllama** [comment]
That’s correct. So we need to do this so the renderers behave the same way.

**Comment by hoch** [comment]
Close this in favor of https://github.com/GoogleChrome/omnitone/pull/89.

**Pull request closed without merging**
