### PR TITLE
Disable normalization of HRTFs, which messes up binaural rendering.

### PR DESCRIPTION
**Pull request by drewbitllama**

### CODE REVIEW

**Comment by hoch** [comment]
Drew, I am in the middle of massing refactoring. I will fix/merge this change locally. Would that be okay?

**Comment by drewbitllama** [comment]
Sounds good--feel free to handle this however you like.

**Comment by drewbitllama** [comment]
Hey Hongchan,

Again, apologies for these changes landed into the same PR. I've added a thorough unit test for hoa-rotator.js, which actually verifies we don't need the sign swap as previously thought. Hence, I've also undone the sign changes in hoa-rotator.js. Cheers!

**Comment by hoch** [comment]
The most recent dev branch has the runnable test.

https://github.com/GoogleChrome/omnitone/tree/dev

**Pull request closed without merging**
