### PR TITLE
Update TOA rotation

### PR DESCRIPTION
**Pull request by hoch**
PTAL.

As discussed in [here](https://github.com/GoogleChrome/omnitone/pull/87#issuecomment-372819574), this PR reverses the rotation direction.

- [Current master](https://rawgit.com/GoogleChrome/omnitone/master/examples/hoa-renderer.html)
- [This PR](https://rawgit.com/GoogleChrome/omnitone/update-toa-rotation/examples/hoa-renderer.html)

I rather not do this at this point unless we can maintain the rotation direction.

### CODE REVIEW

**Comment by drewbitllama** [comment]
The issue is that currently hoa and toa rotate in opposite ways given the
same threejs matrix. This change ensures they rotate in the way.

**Comment by hoch** [comment]
Yes, being able to use the matrix from Three.js is great, but this change breaks other pages that have been using Omnitone this way. Can we consider introducing the new APIs for the better Three.js support? 
1. I think we can go further than changing the sign in the formula. (accessing camera directly?)
2. For the short-term solution, I suggest to use a helper function to do this conversion.

**Comment by drewbitllama** [comment]
Ok sgtm

**Comment by hoch** [comment]
Based on [this discussion](https://github.com/GoogleChrome/omnitone/pull/87#issuecomment-373077337), we decided to bring this change even if it might change the behavior of some pages out there.

1. This is to make the rotation mechanism identical between FOA and HOA renderer.
2. With this change, the rotator directly can take the matrix from Three.js.

**Pull request merged**
